[redis]
host="redis"
port=6379
password=""
db=0
channelKeyPrefix="chan:"
hubKeyPrefix="hub:"

[database]
connection="mysql"
host="mysql"
port=3306
user="root"
password="root"
dbname="chatroom"
charset="utf8mb4"
collation="utf8mb4_unicode_ci"